### ISSUE TITLE
`Stats#dom` is marked private in TS types

### ISSUE THREAD

**Issue by Methuselah96** [RenaudRohlinger/stats-gl#13]
It looks like in one of the recent updates `Stats#dom` was marked private, however it looks like it's being [used publicly](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_lines_fat.html#L143) in three.js example like `webgl_lines_fat.html`. Should the `private` modifier be removed for that property?

**Comment by RenaudRohlinger** [comment]
Ah yes I forgot about this one good catch. 👍

Will deploy a new version tomorrow.

**Comment by RenaudRohlinger** [comment]
Released a fix with 3.1.1.

**Comment by RenaudRohlinger** [comment]
bump to 3.1.2, sorry about that 😄  @Methuselah96

**Comment by alvarosabu** [comment]
Hi @RenaudRohlinger I'm using 3.6.0 and I still having the same issue with `dom` and `container` seems to not be declared on Stats type

![Screenshot 2025-01-04 at 12 45 06
![Screenshot 2025-01-04 at 12 45 45](https://github.com/user-attachments/assets/02b5e1a6-5ec0-48a0-b27c-c9a5179f6d7d)
](https://github.com/user-attachments/assets/e144acf5-c824-4850-a01f-62410b5ae8f5)
