### ISSUE TITLE
Can’t initialize GPU timing for “vanilla” webgl programs

### ISSUE THREAD

**Issue by controversial** [RenaudRohlinger/stats-gl#14]
Before upgrading to v3, I was timing my WebGL code using something like the following:
```ts

constructor() {
  // ...
  this.perfStats = new Stats({ precision: 1 });
  this.perfStats.init(this.canvas);
}

...

draw() {
  this.perfStats.begin();
  // draw
  this.perfStats.end();
}
```

After upgrading to v3, I’ve noticed I need to make the following changes:
- Include `trackGPU: true` in init options
- Call `.update()` after `.end()`

However, even with `trackGPU: true` I don’t have GPU timing:

<img width="216" alt="Screenshot 2024-11-04 at 2 53 08 PM" src="https://github.com/user-attachments/assets/778703d5-ba79-455d-ad4a-955b8aba3ecc">

---

In order to obtain GPU timing, it seems like I need to change my `init` call as follows:

```ts
this.perfStats.init(this.canvas)
  .then(() => {
    this.perfStats.initializeGPUTracking();
  });
```
<img width="294" alt="Screenshot 2024-11-04 at 2 59 31 PM" src="https://github.com/user-attachments/assets/09f53d05-3dff-4985-a84b-5f7553935ac9">

This is because by default `initializeGPUTracking` is *only* called for three.js renderers—even when `trackGPU` is explicitly passed.

However, the `initializeGPUTracking` is marked as private in the source, so Typescript generates build errors if I use it (even though it works at runtime).

Is it intentional that `initializeGPUTracking` is not called, by default, for non-threejs programs passing `trackGpu: true`? Is it intentional that the method is marked as private?

**Comment by RenaudRohlinger** [comment]
Thank you for this! Just released `3.2.0` that should fix the issue.

Also added a new WebGL demo to prevent further breaking changes:
https://stats.renaudrohlinger.com/webgl.html
